title: 'IKT mokyklai'
default_lang: lt
author:
  name: 'Erikas Stanys'
  email: erikas.stanys@gmail.com
taxonomies:
  - kategorija
  - zyma
  - tipas
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
