absolute_urls: false
timezone: Europe/Vilnius
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
force_ssl: false
force_lowercase_urls: true
username_regex: '^[a-z0-9_-]{3,16}$'
pwd_regex: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}'
intl_enabled: true
languages:
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /pradzia
  hide_in_urls: false
pages:
  theme: stack
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: 'Y-m-d H:i'
    short: 'd-m-y G:i'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: false
  twig_first: false
  never_cache_twig: false
  events:
    page: true
    twig: true
  markdown:
    extra: true
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  expires: 604800
  last_modified: false
  etag: false
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '302'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
      - forms
cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: g
  clear_images_by_default: true
  cli_compatibility: false
  lifetime: 604800
  gzip: false
  allow_webserver_gzip: false
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: false
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: false
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
    jquery3: 'theme://js/jquery-3.1.1.min.js'
    bootstrap-css: 'theme://css/bootstrap.css'
    flickity-js: 'theme://js/flickity.min.js'
    flickity-css: 'theme://css/flickity.css'
    easypiechart-js: 'theme://js/easypiechart.min.js'
    parallax-js: 'theme://js/parallax.js'
    typed-js: 'theme://js/typed.min.js'
    datepicker-js: 'theme://js/datepicker.js'
    isotope-js: 'theme://js/isotope.min.js'
    ytplayer-js: 'theme://js/ytplayer.min.js'
    lightbox-js: 'theme://js/lightbox.min.js'
    lightbox-css: 'theme://css/lightbox.min.css'
    granim-js: 'theme://js/granim.min.js'
    steps-js: 'theme://js/jquery.steps.min.js'
    steps-css: 'theme://css/jquery.steps.css'
    countdown-js: 'theme://js/countdown.min.js'
    twitterfetcher-js: 'theme://js/twitterfetcher.min.js'
    spectragram-js: 'theme://js/spectragram.min.js'
    smooth-scroll-js: 'theme://js/smooth-scroll.min.js'
    howler-js: 'theme://js/howler.core.min.js'
    TweenMax-js: 'theme://js/TweenMax.min.js'
    jquery-ui-js: '//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'
    jquery-ui-css: '//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css'
errors:
  display: '1'
  log: true
debugger:
  enabled: false
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 91
  cache_all: false
  cache_perms: '0755'
  debug: false
  auto_fix_orientation: false
media:
  enable_media_timestamp: false
  auto_metadata_exif: false
  upload_limit: 2097152
session:
  enabled: true
  initialize: true
  timeout: 1800
  name: ikt-mokyklai
  secure: false
  httponly: true
  split: true
gpm:
  releases: stable
  method: auto
  verify_peer: true
  official_gpm_only: true
