enabled: true
dropdown:
  enabled: false
dailyrastis_pradinis: /dailyrastis				                        # optional: set root page of documentation
diktantai_pradinis: /diktantai
top_level_version: false                            # Use versions for top level navigation
show_all_pages: false     